version: '3.7'

services:

  db:
    image: postgres:11
    secrets:
      - postgres_password
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 5432:5432
    networks:
      - backend_network
    environment:
      POSTGRES_USER: 'wbooks-api'
      POSTGRES_PASSWORD: 'wbooks-api'
      POSTGRES_DB: 'wbooks-api_development'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ~/docker/volumes/wbooks-api-development
        target: /var/lib/postgresql/data

networks:
  backend_network:

secrets:
  postgres_password:
    external: true
